spring.application.name=backend

# =====================
# server
# =====================
server.port=8080

# =====================
# swagger設定  http://localhost:8080/swagger-ui.html
# =====================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true

# =====================
# Datasource (MySQL in Docker)
# =====================
spring.datasource.url=jdbc:mysql://localhost:3307/woms?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================
# JDBC settings
# =====================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000